// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510151532_AddEmployeeAuthentication")]
    partial class AddEmployeeAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Domain.Entities.Dzial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_dzialu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FirmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_firmy");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nazwa");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("DZIALY", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Firma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_firmy");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nip");

                    b.HasKey("Id");

                    b.HasIndex("Nip")
                        .IsUnique();

                    b.ToTable("FIRMY", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Pracownik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pracownika");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("boolean")
                        .HasColumnName("czy_aktywny");

                    b.Property<long>("DzialId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_dzialu");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hash_hasla");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imie");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rola");

                    b.Property<long>("StanowiskoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_stanowiska");

                    b.HasKey("Id");

                    b.HasIndex("DzialId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("StanowiskoId");

                    b.ToTable("PRACOWNICY", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.PracownikUprawnienie", b =>
                {
                    b.Property<long>("PracownikId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pracownika");

                    b.Property<string>("SygnaturaUprawnienia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sygnatura");

                    b.Property<DateOnly>("DataNadania")
                        .HasColumnType("date")
                        .HasColumnName("data_nadania");

                    b.Property<DateOnly?>("WazneDo")
                        .HasColumnType("date")
                        .HasColumnName("ważne_do");

                    b.HasKey("PracownikId", "SygnaturaUprawnienia");

                    b.HasIndex("SygnaturaUprawnienia");

                    b.ToTable("POSIADA", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Stanowisko", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_stanowiska");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nazwa");

                    b.HasKey("Id");

                    b.ToTable("STANOWISKA", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Uprawnienie", b =>
                {
                    b.Property<string>("Sygnatura")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sygnatura");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("opis");

                    b.Property<long>("PracownikZarzadzajacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pracownika_zarzadzajacego");

                    b.HasKey("Sygnatura");

                    b.HasIndex("PracownikZarzadzajacyId");

                    b.ToTable("UPRAWNIENIA", (string)null);
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Dzial", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Firma", "Firma")
                        .WithMany("Dzialy")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DZIALY_FIRMY_id_firmy");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Pracownik", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Dzial", "Dzial")
                        .WithMany("Pracownicy")
                        .HasForeignKey("DzialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRACOWNICY_DZIALY_id_dzialu");

                    b.HasOne("WebAPI.Domain.Entities.Stanowisko", "Stanowisko")
                        .WithMany("Pracownicy")
                        .HasForeignKey("StanowiskoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRACOWNICY_STANOWISKA_id_stanowiska");

                    b.Navigation("Dzial");

                    b.Navigation("Stanowisko");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.PracownikUprawnienie", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Pracownik", "Pracownik")
                        .WithMany("PracownikUprawnienia")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POSIADA_PRACOWNICY_id_pracownika");

                    b.HasOne("WebAPI.Domain.Entities.Uprawnienie", "Uprawnienie")
                        .WithMany("PracownikUprawnienia")
                        .HasForeignKey("SygnaturaUprawnienia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_POSIADA_UPRAWNIENIA_sygnatura");

                    b.Navigation("Pracownik");

                    b.Navigation("Uprawnienie");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Uprawnienie", b =>
                {
                    b.HasOne("WebAPI.Domain.Entities.Pracownik", "PracownikZarzadzajacy")
                        .WithMany("ZarzadzaneUprawnienia")
                        .HasForeignKey("PracownikZarzadzajacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UPRAWNIENIA_PRACOWNICY_id_pracownika_zarzadzajacego");

                    b.Navigation("PracownikZarzadzajacy");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Dzial", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Firma", b =>
                {
                    b.Navigation("Dzialy");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Pracownik", b =>
                {
                    b.Navigation("PracownikUprawnienia");

                    b.Navigation("ZarzadzaneUprawnienia");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Stanowisko", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("WebAPI.Domain.Entities.Uprawnienie", b =>
                {
                    b.Navigation("PracownikUprawnienia");
                });
#pragma warning restore 612, 618
        }
    }
}
