name: Deploy Pre-built Package to Private Server

on:  
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest image and restart container
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |

          cd /opt/csharp-api

          docker compose pull
          
          docker compose up -d

          docker image prune -f
