name: Deploy to Rocky Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment script
        run: |
          echo "Wdrażam aplikację na moim prywatnym serwerze!"
